services:
  gluetun:
    ports:
      - 8080:8080 #qbittorrent
  unmanic:
    ports:
      - 8888:8888
  jellyfin:
    ports:
      - 8096:8096
  prowlarr:
    ports:
      - 9696:9696
  sonarr:
    ports:
      - 8989:8989
  radarr:
    ports:
      - 7878:7878