
x-common: &common
  environment: &default_env
    TZ: ${TZ:-Etc/UTC}
  restart: unless-stopped

services:
############################
# FLARESOLVERR
############################

  flaresolverr:
    <<: *common
    image: 'ghcr.io/flaresolverr/flaresolverr:latest'
    container_name: flaresolverr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191/health"]

############################
# PROWLARR
############################

  prowlarr:
    <<: *common
    image: 'linuxserver/prowlarr:develop'
    depends_on:
      flaresolverr:
        condition: service_healthy
    volumes:
      - type: volume
        source: trash
        target: /config
        volume:
          subpath: config/prowlarr
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9696"]

volumes:
  trash: ~/trash