
x-common: &common
  user: 0:0
  environment: &default_env
    TZ: ${TZ:-Etc/UTC}
    PUID: 0
    PGID: 0
  restart: unless-stopped

services:
############################
# Whisparr
############################

  whisparr:
    <<: *common
    image: ghcr.io/thespad/whisparr:latest
    environment:
      - SERVICE_URL_WHISPARR_6969
    volumes:
      - '/data/trash/config/whisparr:/config'
      - '/data/trash/data:/data'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6969"]

############################
# RADARR
############################

  radarr:
    <<: *common
    image: 'lscr.io/linuxserver/radarr:latest'
    expose:
      - 7878
    volumes:
      - '/data/trash/config/radarr:/config'
      - '/data/trash/data:/data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/"]
    
############################
# SONARR
############################

  sonarr:
    <<: *common
    image: 'lscr.io/linuxserver/sonarr:latest'
    volumes:
      - '/data/trash/config/sonarr:/config'
      - '/data/trash/data:/data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/"]

############################
# READARR
############################

  readarr:
    <<: *common
    image: lscr.io/linuxserver/readarr:develop
    volumes:
      - '/data/trash/config/readarr:/config'
      - '/data/trash/data:/data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/"]
